# Generated by Django 4.2.3 on 2023-07-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(blank=True, to='mailing.client', verbose_name='Клиент'),
        ),
    ]
